import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import {
  Bell,
  Trash2,
  GitBranch,
  FileText,
  Calendar,
  UserCheck,
  Server,
  AlertTriangle,
  Mail,
  Check
} from 'lucide-react';

interface SystemNotification {
  id: string;
  title: string;
  details: string;
  time: string;
  type: 'git' | 'mom' | 'calendar' | 'leave' | 'system';
  read: boolean;
}

export const Notifications: React.FC = () => {
  const { theme } = useAuth();
  const isDark = theme === 'dark';

  const [notifications, setNotifications] = useState<SystemNotification[]>([
    {
      id: 'notif-1',
      title: 'PR #128 webhook handlers merged',
      details: 'Aarav Rao merged Ankit Sharma\'s branch `feature/webhooks` into `main`. All checks passed.',
      time: '5m ago',
      type: 'git',
      read: false
    },
    {
      id: 'notif-2',
      title: 'New MoM Draft generated by AI',
      details: 'Beta Project - Sprint Review. Discussion points extracted and action items assigned.',
      time: '15m ago',
      type: 'mom',
      read: false
    },
    {
      id: 'notif-3',
      title: 'Meeting reminder: Client Sync',
      details: 'Meeting scheduled in 30 minutes. Venue: Google Meet conference room link.',
      time: '30m ago',
      type: 'calendar',
      read: false
    },
    {
      id: 'notif-4',
      title: 'Leave request authorized',
      details: 'Your leave request for June 29 has been approved by Aarav Rao.',
      time: '1h ago',
      type: 'leave',
      read: true
    },
    {
      id: 'notif-5',
      title: 'Production build pipeline succeeded',
      details: 'Vite build completed for package `g-os-client` (547kB JS, 63kB CSS bundle sizes).',
      time: '2h ago',
      type: 'system',
      read: true
    },
    {
      id: 'notif-6',
      title: 'Decryption pipeline latency alert',
      details: 'Warning: Average transaction webhook response spiked to 1.8 seconds on Paygate sandbox.',
      time: '4h ago',
      type: 'system',
      read: true
    }
  ]);

  const handleMarkRead = (id: string) => {
    setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));
  };

  const handleDelete = (id: string) => {
    setNotifications(prev => prev.filter(n => n.id !== id));
  };

  const handleMarkAllRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  };

  const handleClearAll = () => {
    setNotifications([]);
  };

  const getIcon = (type: SystemNotification['type']) => {
    switch (type) {
      case 'git':
        return <GitBranch className="w-5 h-5 text-indigo-500" />;
      case 'mom':
        return <FileText className="w-5 h-5 text-emerald-500" />;
      case 'calendar':
        return <Calendar className="w-5 h-5 text-amber-500" />;
      case 'leave':
        return <UserCheck className="w-5 h-5 text-rose-500" />;
      case 'system':
        return <Server className="w-5 h-5 text-cyan-500" />;
    }
  };

  return (
    <div className={`p-8 flex flex-col h-[calc(100vh-4rem)] w-full overflow-hidden transition-colors duration-300 ${isDark ? 'bg-[#0c0d14] text-slate-100' : 'bg-slate-50 text-slate-900'}`}>

      {/* Header */}
      <div className="flex items-center justify-between mb-6 flex-shrink-0">
        <div>
          <h1 className={`text-2xl font-bold tracking-tight ${isDark ? 'text-white' : 'text-slate-800'}`}>Notifications</h1>
          <p className="text-xs text-slate-500 font-semibold mt-1">Review activity, pipeline statuses, and leave alerts across the system.</p>
        </div>

        {notifications.length > 0 && (
          <div className="flex items-center gap-2">
            <button
              onClick={handleMarkAllRead}
              className={`flex items-center gap-1.5 px-3 py-2 border rounded-xl text-xs font-semibold transition-colors ${isDark ? 'border-slate-800 hover:bg-slate-800/40 text-slate-300' : 'border-slate-200 hover:bg-slate-50 text-slate-600 shadow-sm'
                }`}
            >
              <Check className="w-3.5 h-3.5" />
              Mark all read
            </button>
            <button
              onClick={handleClearAll}
              className={`flex items-center gap-1.5 px-3 py-2 border border-rose-500/20 bg-rose-500/5 hover:bg-rose-500/10 text-rose-500 rounded-xl text-xs font-semibold transition-colors`}
            >
              <Trash2 className="w-3.5 h-3.5" />
              Clear all
            </button>
          </div>
        )}
      </div>

      {/* Notifications list */}
      <div className={`border rounded-2xl flex-1 overflow-y-auto ${isDark ? 'bg-[#0f1022] border-slate-800/60' : 'bg-white border-slate-200'}`}>
        <div className="divide-y divide-slate-800/40">

          {notifications.map(n => (
            <div key={n.id} className={`p-5 flex items-start justify-between gap-4 hover:bg-slate-800/5 transition-colors ${!n.read ? (isDark ? 'bg-[#141624]/20' : 'bg-indigo-500/5') : ''}`}>
              <div className="flex items-start gap-4">

                {/* Category Icon */}
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center relative ${isDark ? 'bg-slate-900' : 'bg-slate-100'}`}>
                  {getIcon(n.type)}
                  {!n.read && (
                    <span className="absolute -top-0.5 -right-0.5 w-2 h-2 rounded-full bg-indigo-500 ring-2 ring-[#0f1022]" />
                  )}
                </div>

                {/* Content */}
                <div className="space-y-1">
                  <div className="flex items-baseline gap-2">
                    <h3 className={`text-sm font-bold ${isDark ? 'text-white' : 'text-slate-800'}`}>{n.title}</h3>
                    <span className="text-[10px] text-slate-500 font-semibold">{n.time}</span>
                  </div>
                  <p className="text-xs text-slate-500 font-semibold leading-relaxed max-w-2xl">{n.details}</p>
                </div>

              </div>

              {/* Action buttons */}
              <div className="flex items-center gap-2 flex-shrink-0">
                {!n.read && (
                  <button
                    onClick={() => handleMarkRead(n.id)}
                    className={`p-2 rounded-xl border hover:text-indigo-500 transition-colors ${isDark ? 'border-slate-800 hover:bg-slate-800/40 text-slate-400' : 'border-slate-200 hover:bg-slate-50 text-slate-600'}`}
                    title="Mark as read"
                  >
                    <Check className="w-3.5 h-3.5" />
                  </button>
                )}
                <button
                  onClick={() => handleDelete(n.id)}
                  className={`p-2 rounded-xl border hover:text-rose-500 transition-colors ${isDark ? 'border-slate-800 hover:bg-slate-800/40 text-slate-400' : 'border-slate-200 hover:bg-slate-50 text-slate-600'}`}
                  title="Delete"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>

            </div>
          ))}

          {notifications.length === 0 && (
            <div className="py-24 text-center space-y-3">
              <Bell className="w-10 h-10 text-slate-600 mx-auto opacity-50" />
              <p className="text-sm font-bold text-slate-500">You are all caught up!</p>
              <p className="text-xs text-slate-600 font-semibold">No new system or pipeline notifications.</p>
            </div>
          )}

        </div>
      </div>

    </div>
  );
};
export default Notifications;
